---
- name: Haal hostname op
  hosts: 10.42.0.70
  tasks:
    - name: Haal hostname op
      ansible.builtin.hostname:
      register: hostname_output

    - name: Toon hostname
      debug:
        var: hostname_output.stdout
