---
- name: Get current user
  hosts: 10.42.0.138
  tasks:
    - name: Run whoami command
      command: whoami
      register: whoami_output

    - name: Display current user
      debug:
        msg: "Current user is {{ whoami_output.stdout }}"
